<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>AbstractDao.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">internalrule-service</a> &gt; <a href="index.source.html" class="el_package">com.currenciesdirect.gtg.compliance.dbport</a> &gt; <span class="el_source">AbstractDao.java</span></div><h1>AbstractDao.java</h1><pre class="source lang-java linenums">
package com.currenciesdirect.gtg.compliance.dbport;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.currenciesdirect.gtg.compliance.exception.InternalRuleErrors;
import com.currenciesdirect.gtg.compliance.exception.InternalRuleException;

/**
 * The Class AbstractDao.
 */
<span class="fc" id="L22">public abstract class AbstractDao {</span>
<span class="fc" id="L23">	public static final Logger LOG = LoggerFactory.getLogger(AbstractDao.class);</span>

	/** The data source. */
	private DataSource dataSource;
	
	private static final String CONNECTION_ERROR = &quot;Error in closing database connection: &quot;;

	/**
	 * Gets the data source.
	 *
	 * @return the data source
	 * @throws NamingException
	 *             the naming exception
	 */
	public DataSource getDataSource() throws NamingException {
		
		/** The initial context. */
		InitialContext initialContext;

<span class="nc bnc" id="L42" title="All 2 branches missed.">		if (dataSource == null) {</span>
<span class="nc" id="L43">			initialContext = new InitialContext();</span>
<span class="nc" id="L44">			dataSource = (DataSource) initialContext.lookup(&quot;java:jboss/datasources/ComplianceDS&quot;);</span>
		}

<span class="nc" id="L47">		return dataSource;</span>
	}

	/**
	 * Sets the data source.
	 *
	 * @param dataSource
	 *            the new data source
	 */
	public void setDataSource(DataSource dataSource) {
<span class="fc" id="L57">		this.dataSource = dataSource;</span>
<span class="fc" id="L58">	}</span>

	/**
	 * Gets the connection.
	 *
	 * @return the connection
	 * @throws SQLException
	 *             the SQL exception
	 * @throws NamingException
	 *             the naming exception
	 */
	protected Connection getConnection() throws SQLException, NamingException {
<span class="pc bpc" id="L70" title="1 of 2 branches missed.">		if (dataSource == null) {</span>
<span class="nc" id="L71">			getDataSource();</span>
		}
<span class="fc" id="L73">		return dataSource.getConnection();</span>
	}

	/**
	 * Close connection.
	 *
	 * @param con
	 *            the con
	 * @throws SQLException
	 *             the SQL exception
	 * @throws InternalRuleException 
	 */
	protected void closeConnection(Connection con) throws InternalRuleException {
		try {
<span class="pc bpc" id="L87" title="1 of 2 branches missed.">			if (con != null) {</span>
<span class="fc" id="L88">				con.close();</span>
			}
<span class="nc" id="L90">		} catch (Exception e) {</span>
<span class="nc" id="L91">			LOG.error(CONNECTION_ERROR, e);</span>
<span class="nc" id="L92">			throw new InternalRuleException(InternalRuleErrors.DATABASE_GENERIC_ERROR);</span>
<span class="fc" id="L93">		}</span>
<span class="fc" id="L94">	}</span>

	/**
	 * Close prepare statement.
	 *
	 * @param pstmt
	 *            the pstmt
	 * @throws SQLException
	 *             the SQL exception
	 */
	protected void closePrepareStatement(PreparedStatement pstmt) throws InternalRuleException {
		try {
<span class="pc bpc" id="L106" title="1 of 2 branches missed.">			if (pstmt != null) {</span>
<span class="fc" id="L107">				pstmt.close();</span>
			}
<span class="nc" id="L109">		} catch (Exception e) {</span>
<span class="nc" id="L110">			LOG.error(CONNECTION_ERROR, e);</span>
<span class="nc" id="L111">			throw new InternalRuleException(InternalRuleErrors.DATABASE_GENERIC_ERROR);</span>
<span class="fc" id="L112">		}</span>
<span class="fc" id="L113">	}</span>

	/**
	 * Close resultset.
	 *
	 * @param rset
	 *            the rset
	 * @throws SQLException
	 *             the SQL exception
	 */
	protected void closeResultset(ResultSet rset) throws InternalRuleException {
		try {
<span class="fc bfc" id="L125" title="All 2 branches covered.">			if (rset != null) {</span>
<span class="fc" id="L126">				rset.close();</span>
			}
<span class="nc" id="L128">		} catch (Exception e) {</span>
<span class="nc" id="L129">			LOG.error(CONNECTION_ERROR, e);</span>
<span class="nc" id="L130">			throw new InternalRuleException(InternalRuleErrors.DATABASE_GENERIC_ERROR);</span>
<span class="fc" id="L131">		}</span>
<span class="fc" id="L132">	}</span>

	/**
	 * Begin transaction.
	 *
	 * @param con
	 *            the con
	 * @throws SQLException
	 *             the SQL exception
	 */
	protected void beginTransaction(Connection con) throws SQLException {
<span class="fc" id="L143">		con.setAutoCommit(false);</span>
<span class="fc" id="L144">	}</span>

	/**
	 * Commit transaction.
	 *
	 * @param con
	 *            the con
	 * @throws SQLException
	 *             the SQL exception
	 */
	protected void commitTransaction(Connection con) throws SQLException {
<span class="fc" id="L155">		con.commit();</span>
<span class="fc" id="L156">	}</span>

	/**
	 * Transaction rolled back.
	 *
	 * @param con
	 *            the con
	 * @throws SQLException
	 *             the SQL exception
	 */
	protected void transactionRolledBack(Connection con) throws SQLException {
<span class="nc" id="L167">		con.rollback();</span>

<span class="nc" id="L169">	}</span>

}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.5.201910111838</span></div></body></html>